### ISSUE TITLE
Processor name confusion

### ISSUE THREAD

**Issue by git-aniket** [OLIMEX/PIC32-HMZ144#2]
Hi,

The readme in the repo mentions that the current version has a PIC32MZ2048EFG144 processor, but the product page and users manial mentions PIC32MZ2048EFM144 as the processor:
https://www.olimex.com/Products/PIC/Development/PIC32-HMZ144/open-source-hardware

Could you let us know the exact processor in this board.

**Comment by DanKoloff** [comment]
Currently and since last year we've been placing the EFM version - PIC32MZ2048EFM144T-I/PH.

**Comment by git-aniket** [comment]
Thanks
