### ISSUE TITLE
Mistake in PIC32-HMZ144 USER ’ S MANUAL

### ISSUE THREAD

**Issue by git-aniket** [OLIMEX/PIC32-HMZ144#3]
There is a mistake in page 19 of 27 in the data sheet section 6.2.

Datasheet states status LED(green) is connected to pin45(EBIRP/RG2), but actually its connected to RH2.
This can be observed from the schematic on page 10 of the same document.

Datasheet needs updating.

**Comment by DanKoloff** [comment]
The latest datasheet seems correct, refer to the  attached picture:

![seems-correct](https://user-images.githubusercontent.com/6028552/118794046-dd7af380-b8a1-11eb-8153-8a104c1908bc.jpg)

**Comment by git-aniket** [comment]
Yes! Thanks for letting us know.
