### ISSUE TITLE
Regarding layout of peripherals available on pins

### ISSUE THREAD

**Issue by git-aniket** [OLIMEX/PIC32-HMZ144#4]
Hi, 

Is there a layout, say a pdf or image file somewhere detailing the peripherals available on each of the respective pins?
Something like the below-mentioned picture for the Arduino UNO?
The datasheet for HMZ144 on page 8 shows the Pinout but doesn't show the peripherals available.

![arduino UNO layout](https://user-images.githubusercontent.com/31139836/119119035-185c6300-ba2b-11eb-879a-68fdb83d74c7.PNG)

**Comment by DanKoloff** [comment]
Nope we don't have such picture. You can easily connect the picture from the manual with all the peripherals available looking also at the chip's datasheet:

https://ww1.microchip.com/downloads/en/DeviceDoc/PIC32MZ%20EF%20Family%20Datasheet_DS60001320G.pdf

Refer to the table on pages 11 and 12 ("PIN NAMES FOR 144-PIN TQFP DEVICES").
