### ISSUE TITLE
Mounting hole point distances?

### ISSUE THREAD

**Issue by git-aniket** [OLIMEX/PIC32-HMZ144#5]
Hello, 
page 11 of 27 of the manual mentions the physical dimensions of the board.
However, the mounting hole distances are missing from the schematic.
Using the provided info I couldn't calculate the exact values either.

Would it be possible to provide the exact mounting hole distances for the board?

![Physical Dimensions](https://user-images.githubusercontent.com/31139836/119502029-c472b680-bd69-11eb-9580-fef7c481ad3f.PNG)

**Comment by DanKoloff** [comment]
![pic32-hmz144-dimensions](https://user-images.githubusercontent.com/6028552/120279822-93413b80-c2bf-11eb-98ea-79e7d20f4165.png)

It is OSHW board and the design files are available if you find older version of Eagle you can measure anything with the ruler tool.

**Comment by git-aniket** [comment]
Thank You Dan.
